"""empty message

Revision ID: 40fede658fb7
Revises: 
Create Date: 2023-03-07 19:07:55.985700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40fede658fb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Drinks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status')
    )
    op.create_table('waiters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('dismissal_date', sa.Date(), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('waiters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_waiters_dismissal_date'), ['dismissal_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_waiters_hire_date'), ['hire_date'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('waiter', sa.Integer(), nullable=False),
    sa.Column('table', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), server_default='1', nullable=True),
    sa.Column('orders_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['status'], ['status.id'], ),
    sa.ForeignKeyConstraint(['waiter'], ['waiters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), server_default='1', nullable=True),
    sa.Column('status_id', sa.Integer(), server_default='2', nullable=True),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'meal_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal_orders')
    op.drop_table('orders')
    with op.batch_alter_table('waiters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waiters_hire_date'))
        batch_op.drop_index(batch_op.f('ix_waiters_dismissal_date'))

    op.drop_table('waiters')
    op.drop_table('status')
    op.drop_table('meals')
    op.drop_table('Drinks')
    # ### end Alembic commands ###
