"""empty message

Revision ID: 6d03f95563ae
Revises: 40fede658fb7
Create Date: 2023-03-07 22:54:33.527605

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6d03f95563ae'
down_revision = '40fede658fb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('orders_ibfk_1', type_='foreignkey')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('orders_ibfk_1', 'status', ['status'], ['id'])

    # ### end Alembic commands ###
